# Generated by Django 2.2 on 2020-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianModel',
            fields=[
                ('tid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=80)),
                ('tdept', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
