# Generated by Django 2.2 on 2020-01-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_support', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliant_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_no', models.CharField(max_length=20)),
                ('lab_name', models.CharField(max_length=20)),
                ('d_name', models.CharField(max_length=20)),
                ('issue', models.CharField(max_length=100)),
                ('system_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_support.SystemModel')),
            ],
        ),
    ]
