# Generated by Django 2.2 on 2020-01-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_compliant_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliant_model',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
