# Generated by Django 2.0.1 on 2020-01-06 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LabModel',
            fields=[
                ('l_id', models.IntegerField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=30)),
                ('lab_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_support.DepartmentModel')),
            ],
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('system_no', models.IntegerField(primary_key=True, serialize=False)),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_support.LabModel')),
            ],
        ),
    ]
