# Generated by Django 2.2 on 2020-02-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_support', '0002_auto_20200220_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmodel',
            name='lab_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_support.DepartmentModel'),
        ),
    ]
